language: python

dist: jammy

sudo: false
env:
  - TEST_SUITE=samples
  - TEST_SUITE=coverage
python:
  - "3.12"

before_install:
  skip
  # execute all the commands which need to be executed
  # before installing dependencies

install:
  # install all the dependencies we need here
  - pip install pyxb-x==1.2.6
    # can't change the pyxb version without changing the version in setup.py
    # and regenerating the bindings in apicontractsv1.py
  - pip install lxml==4.*
  - pip install requests==2.*
  - if [[ "$TEST_SUITE" == "coverage" ]]; then pip install coverage; fi

before_script:
  # execute all the commands which need to be executed
  # before running actual tests
  - if [[ "$TEST_SUITE" == "samples" ]]; then git submodule update --remote --recursive; fi

script:
  # execute all the tests or other commands to determine
  # whether the build will pass or fail
  - if [[ "$TEST_SUITE" == "coverage" ]]; then coverage run -m unittest discover; coverage report; fi
  - if [[ "$TEST_SUITE" == "samples" ]]; then python setup.py install; cd sample-code-python; python ./test-runner.py; fi
